services:
  notas:
    image: api.registry.viomitra.ru/notas:latest  
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.environment == dev
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.notas-http.rule=Host(`notas-sro.ru`)
        - traefik.http.routers.notas-http.entrypoints=http
        - traefik.http.routers.notas-http.middlewares=https-redirect
        - traefik.http.routers.notas-https.rule=Host(`notas-sro.ru`)
        - traefik.http.routers.notas-https.entrypoints=https
        - traefik.http.routers.notas-https.tls=true
        - traefik.http.routers.notas-https.tls.certresolver=le
        - traefik.http.services.notas.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true